[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python -c 'from app.models.database import init_database; init_database()'"
]

[start]
cmd = "gunicorn -c gunicorn_config.py run:app"
